### ISSUE TITLE
Indentifier expected error

### ISSUE THREAD

**Issue by rustomax** [TakeYourFreedom/Additional-Control-Structures-for-Nim#1]
Thanks, very useful package! Noticed the following error:

```
~/.nimble/pkgs/controlStructures-0.1.0/controlStructures.nim(91, 7)
Error: identifier expected, but found 'keyword with'
```
Main program:
```nim
import controlstructures

let a = 10

unless a > 20:
  echo "Unless works!"
```

BTW, commenting out lines 91 and below, makes the whole package work fine (with the exception of the `with`, of cause)

**Comment by TakeYourFreedom** [comment]
At least in devel 'with' is removed from the keywords-list, but I can't find when it got removed.
I will change it to 'take' for greater combatibility.
